export const program = {
  name: "program",
  title: "Program",
  type: "document",
  fields: [
    { name: "title", title: "Title", type: "string", validation: (Rule: { required: () => unknown }) => Rule.required() },
    { name: "slug", title: "Slug", type: "slug", options: { source: "title" }, validation: (Rule: { required: () => unknown }) => Rule.required() },
    { name: "kicker", title: "Short Kicker", type: "string" },
    { name: "summary", title: "Summary", type: "text" },
    { name: "location", title: "Location", type: "string" },
    {
      name: "status",
      title: "Status",
      type: "string",
      options: { list: [{ title: "Active", value: "active" }, { title: "Planned", value: "planned" }] },
      initialValue: "active",
    },
    { name: "whoBenefits", title: "Who Benefits", type: "text" },
    { name: "whatHappens", title: "What Happens", type: "array", of: [{ type: "string" }] },
    {
      name: "giftUses",
      title: "Donation Use Examples",
      type: "array",
      of: [{ type: "object", fields: [
        { name: "amount", title: "Amount", type: "string" },
        { name: "title", title: "Title", type: "string" },
        { name: "description", title: "Description", type: "text" },
      ] }],
    },
    { name: "outcomes", title: "Expected Outcomes", type: "array", of: [{ type: "string" }] },
    { name: "proofPoints", title: "Donor Proof Points", type: "array", of: [{ type: "string" }] },
    { name: "ctaLabel", title: "Card CTA Label", type: "string" },
    { name: "donationCta", title: "Donation CTA Label", type: "string" },
    { name: "featured", title: "Featured", type: "boolean", initialValue: true },
    { name: "visible", title: "Visible on Website", type: "boolean", initialValue: true },
    { name: "order", title: "Display Order", type: "number" },
    {
      name: "image",
      title: "Program Image",
      type: "image",
      options: { hotspot: true },
      fields: [{ name: "alt", title: "Alt Text", type: "string" }],
    },
  ],
};
